type User {
  email: String! @unique
  name: String!
  trades: [Trade] @relation
  accountDetails: AccountDetails
}
type AccountDetails {
  capital: Float!
  risk: Float!
  leverage: Float!
  open_positions: Int!
  user: User! @relation
}
type Trade {
  ticker: String
  name: String
  basis: Float
  date_purchased: Time
  action: String
  asset_type: String
  platform: String
  status: String
  atr: Float
  trend: String
  oe_score: Float
  notes: String
  sale_price: Float
  gain_loss: Float
  date_sold: Time
  stop_loss: Float
  shares_bought: Float
  shares_sold: Float
  risk_amount: Float
  user: User! @relation
}
type Query {
  userByEmail(email: String!): User!
}

type Mutation {
  register(email: String!, password: String!, name: String!): User! @resolver
  login(email: String!, password: String!): String! @resolver
}
